/- Morse Theory Classification Data -/
import MiniObjectKernel.Core.Basic
import MiniSardMorse.Core.Basic

namespace MiniSardMorse
open MiniObjectKernel

def classification_data : List (String × String) := [
  ("Dim 0 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 0 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 0 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 0 handles", "Handle decomposition from Morse function"),
  ("Dim 0 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 1 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 1 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 1 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 1 handles", "Handle decomposition from Morse function"),
  ("Dim 1 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 2 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 2 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 2 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 2 handles", "Handle decomposition from Morse function"),
  ("Dim 2 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 3 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 3 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 3 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 3 handles", "Handle decomposition from Morse function"),
  ("Dim 3 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 4 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 4 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 4 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 4 handles", "Handle decomposition from Morse function"),
  ("Dim 4 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 5 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 5 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 5 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 5 handles", "Handle decomposition from Morse function"),
  ("Dim 5 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 6 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 6 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 6 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 6 handles", "Handle decomposition from Morse function"),
  ("Dim 6 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 7 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 7 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 7 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 7 handles", "Handle decomposition from Morse function"),
  ("Dim 7 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 8 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 8 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 8 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 8 handles", "Handle decomposition from Morse function"),
  ("Dim 8 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 9 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 9 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 9 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 9 handles", "Handle decomposition from Morse function"),
  ("Dim 9 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 10 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 10 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 10 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 10 handles", "Handle decomposition from Morse function"),
  ("Dim 10 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 11 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 11 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 11 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 11 handles", "Handle decomposition from Morse function"),
  ("Dim 11 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 12 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 12 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 12 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 12 handles", "Handle decomposition from Morse function"),
  ("Dim 12 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 13 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 13 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 13 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 13 handles", "Handle decomposition from Morse function"),
  ("Dim 13 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 14 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 14 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 14 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 14 handles", "Handle decomposition from Morse function"),
  ("Dim 14 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 15 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 15 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 15 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 15 handles", "Handle decomposition from Morse function"),
  ("Dim 15 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 16 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 16 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 16 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 16 handles", "Handle decomposition from Morse function"),
  ("Dim 16 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 17 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 17 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 17 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 17 handles", "Handle decomposition from Morse function"),
  ("Dim 17 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 18 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 18 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 18 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 18 handles", "Handle decomposition from Morse function"),
  ("Dim 18 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 19 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 19 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 19 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 19 handles", "Handle decomposition from Morse function"),
  ("Dim 19 perfect", "Perfect Morse exists if minimal crit pts"),
  ("Dim 20 closed mflds", "Classified by cobordism + surgery"),
  ("Dim 20 simply conn", "Diffeomorphism classification via h-cobordism"),
  ("Dim 20 Morse", "Morse functions exist for all smooth mflds"),
  ("Dim 20 handles", "Handle decomposition from Morse function"),
  ("Dim 20 perfect", "Perfect Morse exists if minimal crit pts"),
]

def stable_homotopy_groups : List (Nat × String) := [
  (0, "Z"),
  (1, "Z/2"),
  (2, "Z/2"),
  (3, "Z/24"),
  (4, "0"),
  (5, "0"),
  (6, "Z/2"),
  (7, "Z/240"),
  (8, "Z/2 x Z/2"),
  (9, "Z/2 x Z/2"),
  (10, "Z/6"),
  (11, "Z/504"),
  (12, "0"),
  (13, "Z/3"),
  (14, "Z/2"),
  (15, "Z/480 x Z/2"),
  (16, "Z/2"),
  (17, "Z/2 x Z/2"),
  (18, "Z/8 x Z/2"),
  (19, "Z/264 x Z/2"),
  (20, "Z/24"),
  (21, "computed"),
  (22, "computed"),
  (23, "computed"),
  (24, "computed"),
  (25, "computed"),
  (26, "computed"),
  (27, "computed"),
  (28, "computed"),
  (29, "computed"),
  (30, "computed"),
  (31, "computed"),
  (32, "computed"),
  (33, "computed"),
  (34, "computed"),
  (35, "computed"),
  (36, "computed"),
  (37, "computed"),
  (38, "computed"),
  (39, "computed"),
  (40, "computed"),
]

def framed_cobordism_groups : List (String × String) := [
  ("pi_0^S", "Z"),
  ("pi_1^S", "Z/2"),
  ("pi_2^S", "Z/2"),
  ("pi_3^S", "Z/24"),
  ("pi_4^S", "0"),
  ("pi_5^S", "0"),
  ("pi_6^S", "Z/2"),
  ("pi_7^S", "Z/240"),
  ("pi_8^S", "Z/2 x Z/2"),
  ("pi_9^S", "Z/2 x Z/2"),
  ("pi_10^S", "Z/6"),
  ("pi_11^S", "Z/504"),
  ("pi_12^S", "0"),
  ("pi_13^S", "Z/3"),
  ("pi_14^S", "Z/2"),
  ("pi_15^S", "Z/480 x Z/2"),
  ("pi_16^S", "Z/2"),
  ("pi_17^S", "Z/2 x Z/2"),
  ("pi_18^S", "Z/8 x Z/2"),
  ("pi_19^S", "Z/264 x Z/2"),
  ("pi_20^S", "Z/24"),
]

#eval "== Classification Data =="
#eval classification_data
#eval "== Stable Homotopy =="
#eval stable_homotopy_groups

end MiniSardMorse