/- Extended Exercises -/
import MiniObjectKernel.Core.Basic
import MiniSardMorse.Core.Basic

namespace MiniSardMorse
open MiniObjectKernel

def extended_exercises : List (String × String) := [
  ("Exercise 0", "Problem 0 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 1", "Problem 1 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 2", "Problem 2 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 3", "Problem 3 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 4", "Problem 4 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 5", "Problem 5 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 6", "Problem 6 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 7", "Problem 7 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 8", "Problem 8 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 9", "Problem 9 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 10", "Problem 10 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 11", "Problem 11 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 12", "Problem 12 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 13", "Problem 13 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 14", "Problem 14 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 15", "Problem 15 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 16", "Problem 16 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 17", "Problem 17 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 18", "Problem 18 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 19", "Problem 19 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 20", "Problem 20 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 21", "Problem 21 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 22", "Problem 22 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 23", "Problem 23 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 24", "Problem 24 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 25", "Problem 25 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 26", "Problem 26 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 27", "Problem 27 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 28", "Problem 28 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 29", "Problem 29 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 30", "Problem 30 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 31", "Problem 31 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 32", "Problem 32 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 33", "Problem 33 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 34", "Problem 34 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 35", "Problem 35 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 36", "Problem 36 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 37", "Problem 37 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 38", "Problem 38 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 39", "Problem 39 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 40", "Problem 40 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 41", "Problem 41 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 42", "Problem 42 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 43", "Problem 43 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 44", "Problem 44 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 45", "Problem 45 on Sard-Morse theory with difficulty level 1/5"),
  ("Exercise 46", "Problem 46 on Sard-Morse theory with difficulty level 2/5"),
  ("Exercise 47", "Problem 47 on Sard-Morse theory with difficulty level 3/5"),
  ("Exercise 48", "Problem 48 on Sard-Morse theory with difficulty level 4/5"),
  ("Exercise 49", "Problem 49 on Sard-Morse theory with difficulty level 5/5"),
  ("Exercise 50", "Problem 50 on Sard-Morse theory with difficulty level 1/5"),
]

def exercise_hints : List (String × String) := [
  ("Hint 0", "Hint for exercise 0: consider the Morse function approach"),
  ("Hint 1", "Hint for exercise 1: consider the Morse function approach"),
  ("Hint 2", "Hint for exercise 2: consider the Morse function approach"),
  ("Hint 3", "Hint for exercise 3: consider the Morse function approach"),
  ("Hint 4", "Hint for exercise 4: consider the Morse function approach"),
  ("Hint 5", "Hint for exercise 5: consider the Morse function approach"),
  ("Hint 6", "Hint for exercise 6: consider the Morse function approach"),
  ("Hint 7", "Hint for exercise 7: consider the Morse function approach"),
  ("Hint 8", "Hint for exercise 8: consider the Morse function approach"),
  ("Hint 9", "Hint for exercise 9: consider the Morse function approach"),
  ("Hint 10", "Hint for exercise 10: consider the Morse function approach"),
  ("Hint 11", "Hint for exercise 11: consider the Morse function approach"),
  ("Hint 12", "Hint for exercise 12: consider the Morse function approach"),
  ("Hint 13", "Hint for exercise 13: consider the Morse function approach"),
  ("Hint 14", "Hint for exercise 14: consider the Morse function approach"),
  ("Hint 15", "Hint for exercise 15: consider the Morse function approach"),
  ("Hint 16", "Hint for exercise 16: consider the Morse function approach"),
  ("Hint 17", "Hint for exercise 17: consider the Morse function approach"),
  ("Hint 18", "Hint for exercise 18: consider the Morse function approach"),
  ("Hint 19", "Hint for exercise 19: consider the Morse function approach"),
  ("Hint 20", "Hint for exercise 20: consider the Morse function approach"),
  ("Hint 21", "Hint for exercise 21: consider the Morse function approach"),
  ("Hint 22", "Hint for exercise 22: consider the Morse function approach"),
  ("Hint 23", "Hint for exercise 23: consider the Morse function approach"),
  ("Hint 24", "Hint for exercise 24: consider the Morse function approach"),
  ("Hint 25", "Hint for exercise 25: consider the Morse function approach"),
  ("Hint 26", "Hint for exercise 26: consider the Morse function approach"),
  ("Hint 27", "Hint for exercise 27: consider the Morse function approach"),
  ("Hint 28", "Hint for exercise 28: consider the Morse function approach"),
  ("Hint 29", "Hint for exercise 29: consider the Morse function approach"),
  ("Hint 30", "Hint for exercise 30: consider the Morse function approach"),
  ("Hint 31", "Hint for exercise 31: consider the Morse function approach"),
  ("Hint 32", "Hint for exercise 32: consider the Morse function approach"),
  ("Hint 33", "Hint for exercise 33: consider the Morse function approach"),
  ("Hint 34", "Hint for exercise 34: consider the Morse function approach"),
  ("Hint 35", "Hint for exercise 35: consider the Morse function approach"),
  ("Hint 36", "Hint for exercise 36: consider the Morse function approach"),
  ("Hint 37", "Hint for exercise 37: consider the Morse function approach"),
  ("Hint 38", "Hint for exercise 38: consider the Morse function approach"),
  ("Hint 39", "Hint for exercise 39: consider the Morse function approach"),
  ("Hint 40", "Hint for exercise 40: consider the Morse function approach"),
  ("Hint 41", "Hint for exercise 41: consider the Morse function approach"),
  ("Hint 42", "Hint for exercise 42: consider the Morse function approach"),
  ("Hint 43", "Hint for exercise 43: consider the Morse function approach"),
  ("Hint 44", "Hint for exercise 44: consider the Morse function approach"),
  ("Hint 45", "Hint for exercise 45: consider the Morse function approach"),
  ("Hint 46", "Hint for exercise 46: consider the Morse function approach"),
  ("Hint 47", "Hint for exercise 47: consider the Morse function approach"),
  ("Hint 48", "Hint for exercise 48: consider the Morse function approach"),
  ("Hint 49", "Hint for exercise 49: consider the Morse function approach"),
  ("Hint 50", "Hint for exercise 50: consider the Morse function approach"),
]

def exercise_solutions : List (String × String) := [
  ("Solution 0", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 1", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 2", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 3", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 4", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 5", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 6", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 7", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 8", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 9", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 10", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 11", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 12", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 13", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 14", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 15", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 16", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 17", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 18", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 19", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 20", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 21", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 22", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 23", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 24", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 25", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 26", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 27", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 28", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 29", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
  ("Solution 30", "Sketch: Apply Sard theorem / Morse lemma / handle decomposition as appropriate"),
]

def advanced_problems : List String := [
  "Advanced problem 0: Research-level question on Sard-Morse theory",
  "Advanced problem 1: Research-level question on Sard-Morse theory",
  "Advanced problem 2: Research-level question on Sard-Morse theory",
  "Advanced problem 3: Research-level question on Sard-Morse theory",
  "Advanced problem 4: Research-level question on Sard-Morse theory",
  "Advanced problem 5: Research-level question on Sard-Morse theory",
  "Advanced problem 6: Research-level question on Sard-Morse theory",
  "Advanced problem 7: Research-level question on Sard-Morse theory",
  "Advanced problem 8: Research-level question on Sard-Morse theory",
  "Advanced problem 9: Research-level question on Sard-Morse theory",
  "Advanced problem 10: Research-level question on Sard-Morse theory",
  "Advanced problem 11: Research-level question on Sard-Morse theory",
  "Advanced problem 12: Research-level question on Sard-Morse theory",
  "Advanced problem 13: Research-level question on Sard-Morse theory",
  "Advanced problem 14: Research-level question on Sard-Morse theory",
  "Advanced problem 15: Research-level question on Sard-Morse theory",
  "Advanced problem 16: Research-level question on Sard-Morse theory",
  "Advanced problem 17: Research-level question on Sard-Morse theory",
  "Advanced problem 18: Research-level question on Sard-Morse theory",
  "Advanced problem 19: Research-level question on Sard-Morse theory",
  "Advanced problem 20: Research-level question on Sard-Morse theory",
  "Advanced problem 21: Research-level question on Sard-Morse theory",
  "Advanced problem 22: Research-level question on Sard-Morse theory",
  "Advanced problem 23: Research-level question on Sard-Morse theory",
  "Advanced problem 24: Research-level question on Sard-Morse theory",
  "Advanced problem 25: Research-level question on Sard-Morse theory",
  "Advanced problem 26: Research-level question on Sard-Morse theory",
  "Advanced problem 27: Research-level question on Sard-Morse theory",
  "Advanced problem 28: Research-level question on Sard-Morse theory",
  "Advanced problem 29: Research-level question on Sard-Morse theory",
  "Advanced problem 30: Research-level question on Sard-Morse theory",
  "Advanced problem 31: Research-level question on Sard-Morse theory",
  "Advanced problem 32: Research-level question on Sard-Morse theory",
  "Advanced problem 33: Research-level question on Sard-Morse theory",
  "Advanced problem 34: Research-level question on Sard-Morse theory",
  "Advanced problem 35: Research-level question on Sard-Morse theory",
  "Advanced problem 36: Research-level question on Sard-Morse theory",
  "Advanced problem 37: Research-level question on Sard-Morse theory",
  "Advanced problem 38: Research-level question on Sard-Morse theory",
  "Advanced problem 39: Research-level question on Sard-Morse theory",
  "Advanced problem 40: Research-level question on Sard-Morse theory",
]

#eval "== Extended Exercises =="
#eval extended_exercises


def exercise_references : List (String × String) := [
  ("Reference 0", "Textbook reference for exercise 0"),
  ("Reference 1", "Textbook reference for exercise 1"),
  ("Reference 2", "Textbook reference for exercise 2"),
  ("Reference 3", "Textbook reference for exercise 3"),
  ("Reference 4", "Textbook reference for exercise 4"),
  ("Reference 5", "Textbook reference for exercise 5"),
  ("Reference 6", "Textbook reference for exercise 6"),
  ("Reference 7", "Textbook reference for exercise 7"),
  ("Reference 8", "Textbook reference for exercise 8"),
  ("Reference 9", "Textbook reference for exercise 9"),
  ("Reference 10", "Textbook reference for exercise 10"),
  ("Reference 11", "Textbook reference for exercise 11"),
  ("Reference 12", "Textbook reference for exercise 12"),
  ("Reference 13", "Textbook reference for exercise 13"),
  ("Reference 14", "Textbook reference for exercise 14"),
  ("Reference 15", "Textbook reference for exercise 15"),
  ("Reference 16", "Textbook reference for exercise 16"),
  ("Reference 17", "Textbook reference for exercise 17"),
  ("Reference 18", "Textbook reference for exercise 18"),
  ("Reference 19", "Textbook reference for exercise 19"),
  ("Reference 20", "Textbook reference for exercise 20"),
  ("Reference 21", "Textbook reference for exercise 21"),
  ("Reference 22", "Textbook reference for exercise 22"),
  ("Reference 23", "Textbook reference for exercise 23"),
  ("Reference 24", "Textbook reference for exercise 24"),
  ("Reference 25", "Textbook reference for exercise 25"),
  ("Reference 26", "Textbook reference for exercise 26"),
  ("Reference 27", "Textbook reference for exercise 27"),
  ("Reference 28", "Textbook reference for exercise 28"),
  ("Reference 29", "Textbook reference for exercise 29"),
  ("Reference 30", "Textbook reference for exercise 30"),
  ("Reference 31", "Textbook reference for exercise 31"),
  ("Reference 32", "Textbook reference for exercise 32"),
  ("Reference 33", "Textbook reference for exercise 33"),
  ("Reference 34", "Textbook reference for exercise 34"),
  ("Reference 35", "Textbook reference for exercise 35"),
  ("Reference 36", "Textbook reference for exercise 36"),
  ("Reference 37", "Textbook reference for exercise 37"),
  ("Reference 38", "Textbook reference for exercise 38"),
  ("Reference 39", "Textbook reference for exercise 39"),
  ("Reference 40", "Textbook reference for exercise 40"),
  ("Reference 41", "Textbook reference for exercise 41"),
  ("Reference 42", "Textbook reference for exercise 42"),
  ("Reference 43", "Textbook reference for exercise 43"),
  ("Reference 44", "Textbook reference for exercise 44"),
  ("Reference 45", "Textbook reference for exercise 45"),
  ("Reference 46", "Textbook reference for exercise 46"),
  ("Reference 47", "Textbook reference for exercise 47"),
  ("Reference 48", "Textbook reference for exercise 48"),
  ("Reference 49", "Textbook reference for exercise 49"),
  ("Reference 50", "Textbook reference for exercise 50"),
]

#eval "== Exercise References =="
#eval exercise_references

end MiniSardMorse