/- FAQ -/
import MiniObjectKernel.Core.Basic
import MiniSardMorse.Core.Basic

namespace MiniSardMorse
open MiniObjectKernel

def FAQ : List (String × String) := [
  ("What is Sard theorem?", "Critical values of Ck map have measure zero if k >= max(1,m-n+1)"),
  ("What is a Morse function?", "Smooth function whose critical points are all nondegenerate"),
  ("What is Morse index?", "Number of negative eigenvalues of Hessian at critical point"),
  ("What is Morse lemma?", "Near crit pt: f(x) = f(p) - x1^2 - ... - xk^2 + x_{k+1}^2 + ... + xn^2"),
  ("What are Morse inequalities?", "mk >= bk (weak); alt sum bound (strong); lacunary principle"),
  ("What is handle decomposition?", "Decomposition into Dk * D^{n-k} attached along S^{k-1} * D^{n-k}"),
  ("What is Reeb theorem?", "Closed manifold + Morse fn with 2 crit pts = sphere"),
  ("What is Morse homology?", "Chain complex Ck generated by crit pts of index k; boundary = flow line count"),
  ("What is Floer homology?", "Infinite-dim generalization to loop spaces (Lagrangian, instanton, Heegaard)"),
  ("What is h-cobordism?", "Simply connected h-cobordisms of dim>=5 are products (Smale 1961)"),
  ("What is Morse-Bott theory?", "Generalization allowing critical manifolds instead of isolated points"),
  ("What is equivariant Morse?", "Morse theory for G-invariant functions; Atiyah-Bott localization"),
  ("Why is Morse theory important?", "Connects analysis (crit pts) to topology (homology)"),
  ("What is Bott periodicity?", "pi_{k+2}(O) = pi_k(O) proved via Morse on loop spaces of symmetric spaces"),
  ("Arnold conjecture?", "Fixed points of Hamiltonian diffeo >= sum of Betti numbers"),
  ("Exotic spheres?", "Smooth manifolds homeomorphic but not diffeomorphic to spheres; Theta_7 = Z/28"),
  ("Kervaire invariant?", "Invariant of (4k+2)-manifolds; 1 only in dim 2,6,14,30,62 (HHR 2016)"),
  ("Cerf theory?", "Study of 1-parameter families of Morse functions; pseudoisotopy"),
  ("Discrete Morse theory?", "Combinatorial Morse theory for simplicial complexes (Forman 1998)"),
  ("How to compute Morse homology?", "Count gradient flow lines between crit pts of consecutive indices"),
  ("What is a Morse-Smale function?", "Morse fn where stable/unstable manifolds intersect transversely"),
  ("What is the Smale condition?", "Stable and unstable manifolds of gradient flow intersect transversely"),
  ("Thom transversality?", "Any smooth map can be perturbed to be transverse to a submanifold"),
  ("What is a perfect Morse function?", "Morse function with mk = bk for all k (no cancellations)"),
  ("Lacunary principle?", "If mk * m_{k+1} = 0 for all k, then mk = bk (perfect Morse)"),
  ("Handle cancellation?", "Pair of handles (k,k+1) can be cancelled if attaching sphere meets belt sphere once"),
  ("s-cobordism?", "h-cobordism trivial iff Whitehead torsion vanishes (dim>=6)"),
  ("Whitehead torsion?", "Algebraic K1 invariant measuring obstruction to simple homotopy equivalence"),
  ("What is the Smale conjecture?", "Diff(S^3) is homotopy equivalent to O(4) (proved by Hatcher)"),
  ("Poincare conjecture?", "Every simply connected closed 3-manifold is S^3 (Perelman 2003)"),
]

#eval "== FAQ =="
#eval FAQ

end MiniSardMorse