/- Glossary -/
import MiniObjectKernel.Core.Basic
import MiniSardMorse.Core.Basic

namespace MiniSardMorse
open MiniObjectKernel

def glossary : List (String × String) := [
  ("Sard Theorem", "Critical values of Ck map have measure zero if k >= max(1,m-n+1)"),
  ("Morse Function", "Smooth function with nondegenerate critical points only"),
  ("Critical Point", "Point where differential has rank less than maximum"),
  ("Regular Value", "Value not in the image of the critical set"),
  ("Morse Index", "Number of negative eigenvalues of the Hessian matrix"),
  ("Handle", "Product Dk * D^{n-k} attached along S^{k-1} * D^{n-k}"),
  ("Handle Decomposition", "Decomposition of a manifold into handles"),
  ("CW Complex", "Closure-finite weak topology cell complex"),
  ("Gradient Flow", "Flow along negative gradient of a Morse function"),
  ("Morse-Smale", "Stable and unstable manifolds intersect transversely"),
  ("Morse Homology", "Homology from chain complex generated by critical points"),
  ("Reeb Graph", "Graph encoding level set topology of a Morse function"),
  ("Morse-Bott", "Morse theory with critical manifolds instead of isolated points"),
  ("Equivariant Morse", "Morse theory for G-invariant functions on G-manifolds"),
  ("h-Cobordism", "Cobordism where inclusions are homotopy equivalences"),
  ("Floer Homology", "Infinite-dimensional Morse theory on loop spaces"),
  ("Morse Polynomial", "M_f(t) = sum m_k tk counting critical points by index"),
  ("Poincare Polynomial", "P_M(t) = sum b_k tk for Betti numbers"),
  ("Euler Characteristic", "chi = sum (-1)^k b_k = sum (-1)^k m_k"),
  ("Perfect Morse", "Morse function with exactly b_k critical points of index k"),
  ("Handlebody", "Manifold built entirely from handles"),
  ("Kirby Diagram", "Link diagram describing 4-manifold handle decomposition"),
  ("Cerf Theory", "Study of 1-parameter families of Morse functions"),
  ("Pseudoisotopy", "Isotopy of diffeomorphisms; related to Cerf theory"),
  ("Birth-Death", "Creation/annihilation of critical point pairs in families"),
]

#eval "== Glossary =="
#eval glossary

end MiniSardMorse
