/- Survey of Sard-Morse Theory -/
import MiniObjectKernel.Core.Basic
import MiniSardMorse.Core.Basic

namespace MiniSardMorse
open MiniObjectKernel

def survey : List String := [
  "Sard theorem: The set of critical values of Ck map f: M^m -> N^n has measure zero if k >= max(1,m-n+1).",
  "Morse lemma: Near a nondegenerate critical point of index k, f(x) = f(p) - sum_{i=1}^k xi^2 + sum_{i=k+1}^n xi^2.",
  "Morse inequalities: Weak form: mk >= bk. Strong form: sum_{i=0}^k (-1)^{k-i} mi >= sum_{i=0}^k (-1)^{k-i} bi.",
  "Handle decomposition: A Morse function gives a handle decomposition with one k-handle per critical point of index k.",
  "CW structure: Morse functions provide CW complex structures on manifolds.",
  "Gradient flow: Flow lines of -grad(f) connect critical points of decreasing index.",
  "Morse homology: Chain complex Ck generated by critical points of index k, boundary counts gradient flow lines.",
  "Reeb theorem: Closed manifold with exactly 2 critical points = sphere.",
  "h-cobordism: Simply connected h-cobordisms of dim>=5 are trivial (Smale 1961).",
  "Floer homology: Infinite-dimensional Morse theory on loop spaces.",
  "Morse-Bott: Generalization allowing critical manifolds instead of isolated critical points.",
  "Equivariant Morse: Morse theory in the presence of group actions.",
  "The fundamental idea: The topology of a manifold can be understood by studying generic smooth functions on it.",
  "Key insight: Critical points encode the homotopy type of sublevel sets.",
  "Method: Attach handles at critical points to build the manifold from simple pieces.",
  "Applications: From proving the Poincare conjecture to computing Floer homology.",
  "Modern perspective: Morse theory as a tool in homological algebra and category theory.",
  "Future directions: Derived Morse theory, categorification, and connections to quantum field theory.",
  "Unifying theme: Morse theory bridges differential topology, algebraic topology, and geometric analysis.",
  "Educational value: Morse theory exemplifies the unity of mathematics.",
]

#eval "== Survey =="
#eval survey

end MiniSardMorse
