import MiniObjectKernel.Core.Basic
import MiniCobordism.Core.Basic
namespace MiniCobordism
open MiniObjectKernel

def dimensionFacts : List (Nat × String) := [
  (0, "Point: generates O_0^SO = Z; O_0^O = Z/2"),
  (1, "Every closed 1-manifold bounds (circle bounds disk)"),
  (2, "RP^2 generates O_2^O = Z/2; all oriented surfaces bound"),
  (3, "Every closed oriented 3-manifold bounds (O_3^SO = 0)"),
  (4, "CP^2 generates O_4^SO = Z; K3 has sigma=-16"),
  (5, "Wu manifold SU(3)/SO(3) generates Z/2 in O_5^SO"),
  (6, "O_6^SO = 0; O_6^O = (Z/2)^3"),
  (7, "28 exotic 7-spheres (Milnor); O_7^fr = Z/240"),
  (8, "O_8^SO = Z+Z generated by CP^4 and HP^2"),
  (9, "O_9^SO = (Z/2)^2; O_9^fr = (Z/2)^3"),
  (10, "O_10^SO = Z/2; O_10^fr = Z/6")
]

def surgeryDimensions : List (Nat × String) := [
  (1, "Surgery on S^0: connected sum"),
  (2, "Surgery on S^1: Dehn surgery on 3-manifolds"),
  (3, "Surgery on S^2: 4-manifold topology"),
  (4, "Surgery on S^3: exotic structures"),
  (5, "Surgery dim >= 5: Wall classification theory")
]

def groupNames : List (String × String) := [
  ("O", "Orthogonal group: unoriented cobordism"),
  ("SO", "Special orthogonal: oriented cobordism"),
  ("U", "Unitary: complex cobordism"),
  ("SU", "Special unitary: Calabi-Yau structures"),
  ("Sp", "Symplectic: quaternionic structures"),
  ("Spin", "Spin: spin cobordism (A-hat genus)"),
  ("String", "String: string cobordism (Witten genus)"),
  ("G", "Spherical fibrations: normal invariants"),
  ("Top", "Homeomorphisms: topological manifolds"),
  ("PL", "Piecewise linear: PL manifolds")
]

def famousFormulas : List String := [
  "O_n = pi_{n+k}(MO(k))  (Pontryagin-Thom, k >> n)",
  "N_* = F_2[x_2, x_4, x_5, x_6, x_8, ...]  (Thom 1954)",
  "sigma(M) = <L_k(p_1,...,p_k), [M]>  (Hirzebruch 1954)",
  "index(D) = <A-hat(M) ch(E), [M]>  (Atiyah-Singer 1963)",
  "p_1[M^4] = 3*sigma(M)  (Hirzebruch signature in dim 4)",
  "MU_*(X) (x)_{MU_*} Z = K^*(X)  (Conner-Floyd 1966)",
  "bP_{n+1} = Theta_n / (coker J)_n  (Kervaire-Milnor 1963)",
  "Sp = holim L_n Sp  (chromatic convergence, Hopkins-Ravenel)",
  "Z: Bord_n^fr -> C ~ C^{fd}  (cobordism hypothesis, Lurie)"
]

def categoryDifferences : List (Nat × String) := [
  (1, "DIFF = PL = TOP (trivial in dimension 1)"),
  (2, "DIFF = PL = TOP (Rado 1925)"),
  (3, "DIFF = PL = TOP (Moise 1952)"),
  (4, "DIFF != TOP (Freedman 1982: TOP h-cobordism holds)"),
  (5, "DIFF = PL = TOP (h-cobordism + smoothing)"),
  (6, "DIFF = PL = TOP (same as dim 5)"),
  (7, "DIFF = PL = TOP (stable range, same proof)")
]

def invariantsSummary : List (String × String × String) := [
  ("Unoriented", "Stiefel-Whitney numbers", "N_*: complete classification"),
  ("Oriented", "Pontryagin numbers + signature", "O_*^SO: rationally complete"),
  ("Complex", "Chern numbers", "MU_*: complete (torsion-free)"),
  ("Framed", "Adams e-invariant", "O_*^fr = pi_*^S"),
  ("Spin", "A-hat genus (integer)", "O_*^Spin: related to O_*^SO"),
  ("String", "Witten genus (TMF-valued)", "O_*^String: related to TMF")
]

#eval "== Almanac =="
#eval dimensionFacts
#eval surgeryDimensions
#eval groupNames
#eval famousFormulas
#eval categoryDifferences
#eval invariantsSummary


end MiniCobordism
